#!/usr/bin/env python3
import urllib.request
import argparse
import json
import webbrowser

parser = argparse.ArgumentParser()
parser.add_argument("bronze")
parser.add_argument("silver")
parser.add_argument("gold")
parser.add_argument("-o", "--open", action="store_true", help="Open in web browser topics for all Bronze badges that have not also earned a silver.")
args = parser.parse_args()
bronze = args.bronze
silver = args.silver
gold = args.gold

badgeUrl = 'https://literatecomputing.com/user_badges.json?badge_id={0}'

printed={}
for badgeColor in (gold, silver, bronze):

    with urllib.request.urlopen(badgeUrl.format(str(badgeColor))) as response:
        badges = response.read().decode("utf-8")

    memberinfo=json.loads(badges)
    users={}
    print ("\n\n-------------------- Badge: {0}({1}) --------------------".format(memberinfo['badges'][0]['name'], memberinfo['badges'][0]['id']))
    for member in (memberinfo['users']):
        users[(member['id'])]=member['username']

    for badge in (memberinfo['user_badge_info']['user_badges']):
        if badge['user_id'] in printed:
            url=""
        else:
            url="http://literatecomputing.com/t/{0}".format(badge['topic_id'])
            printed[badge['user_id']]=badgeColor
        print("user_id: {0} {1}".format(users[badge['user_id']], url))
        if (badgeColor == bronze) and (url != ""):
            if args.open:
                webbrowser.open(url)


